Win-probability
========================================================


イニング, 裏表, 点差, ランナー状況別に, 勝率を集計したいです. 

例えば, 2点ビハインドの7回裏で, 2アウト満塁の場面から勝つ確率は何%か, みたいなことを知りたいです. 

データ読み込み.
```{r}
library(data.table)
library(dplyr)
library(reshape2)
library(xtable)
dat = fread("../../../../data/all2013.csv")
name = fread("../names.csv", header=FALSE) %>% unlist
dat %>% setnames(name)
```

試合別に, home/awayのどちらが勝ったかを調べる. 
とりあえず引き分けはホームの負けとしておく.
```{r}
dat_win = 
  dat %>% 
  group_by(GAME_ID) %>%
  dplyr::summarise(HOME_SCORE = tail(HOME_SCORE_CT,1), 
                   AWAY_SCORE = tail(AWAY_SCORE_CT,1)) %>% 
  mutate(HOME_WIN = ifelse(HOME_SCORE>AWAY_SCORE, 1, 0) )%>% 
  select(GAME_ID, HOME_WIN)
dat_win
```

ランナー状況, イニング, 点差を抽出する.
```{r}
dat_select_for_wp = 
  dat %>% 
  mutate(RUNNERS= (BASE3_RUN_ID!="")*100 + (BASE2_RUN_ID!="")*10 + (BASE1_RUN_ID!="")*1) %>% 
  mutate(HOME_AWAY = HOME_SCORE_CT - AWAY_SCORE_CT) %>% 
  select(GAME_ID, INN_CT, BAT_HOME_ID, OUTS_CT, RUNNERS, HOME_AWAY)

dat_select_for_wp
```

結合する. 

```{r}
dat_for_wp =
  dat_select_for_wp %>% 
  dplyr::inner_join(dat_win, by = "GAME_ID") %>% 
  group_by(INN_CT, BAT_HOME_ID, OUTS_CT, RUNNERS, HOME_AWAY) %>%
  dplyr::summarise(HOME_LOSES = sum(HOME_WIN), GAMES = n()) %>%
  mutate(HOME_WINS = GAMES - HOME_LOSES)

dat_for_wp

## ホームゲームアドバンテージ
dat_for_wp %>% 
  dplyr::filter(INN_CT == 1 & OUTS_CT == 0 & RUNNERS == 0 & HOME_AWAY==0 & BAT_HOME_ID == 0) %>% 
  dplyr::mutate(HOME_WIN_RATE = HOME_WINS/GAMES, AWAY_WIN_RATE = HOME_LOSES/GAMES)
```


